const catchError = (err) => {
	console.log(err);
};

module.exports = {
	catchError
};